### ISSUE TITLE
Strange ID that database cannot parse

### ISSUE THREAD

**Issue by arduino-man** [wasitanbits/secruex#2]
Following the documentation to the letter I get the following error when trying to create my first permission:  

`
iex(4)> SecureX.Permissions.add(%{"permission" => -1, "resource_id" => "users", "role_id" => "super_admin"})
[debug] QUERY OK source="permissions" db=0.8ms queue=0.9ms idle=871.7ms
SELECT p0."id", p0."permission", p0."resource_id", p0."role_id", p0."inserted_at", p0."updated_at" FROM "permissions" AS p0 WHERE ((p0."resource_id" = $1) AND (p0."role_id" = $2)) ["users", "super_admin"]
[debug] QUERY ERROR db=5.3ms queue=0.4ms idle=887.6ms
INSERT INTO "permissions" ("permission","resource_id","role_id","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6) [-1, "users", "super_admin", ~U[2022-07-29 22:01:52Z], ~U[2022-07-29 22:01:52Z], <<229, 93, 134, 93, 32, 245, 77, 115, 148, 211, 44, 9, 6, 17, 106, 115>>]
** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got <<229, 93, 134, 93, 32, 245, 77, 115, 148, 211, 44, 9, 6, 17, 106, 115>>. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.15.13) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.15.13) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.4.1) lib/db_connection.ex:1224: DBConnection.encode/5
    (db_connection 2.4.1) lib/db_connection.ex:1324: DBConnection.run_prepare_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:1428: DBConnection.run/6
    (db_connection 2.4.1) lib/db_connection.ex:593: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:585: DBConnection.prepare_execute/4
    (postgrex 0.15.13) lib/postgrex.ex:292: Postgrex.query/4
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:802: Ecto.Adapters.SQL.struct/10
    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (securex 1.0.5) lib/securex_web/controllers/permission_controller.ex:61: SecureXWeb.PermissionController.create_per/1
    (securex 1.0.5) lib/securex_permissions.ex:68: SecureX.Permissions.add/1

`

**Comment by arduino-man** [comment]
I apologize for the look of that, I was not able to paste the error using the code tags.

I am having an issue understanding the purpose of "id" in the query which gets translated into: <<229, 93, 134, 93, 32, 245, 77, 115, 148, 211, 44, 9, 6, 17, 106, 115>>

**Comment by wasibiit** [comment]
@arduino-man Hi 
i think you are using `UUID`'s as Primary Key for your tables, 
By Default migrations gets sipped out with `mix securex.gen.migration` for `Integer` Type of Primary Key, 

if you are using `UUID`'s, you need to specify type in your config for `:securex`, 
Follow These steps might help you , 
```
# config/config.exs

config :securex, repo: MyApp.Repo,
   schema: MyApp.Schema.User,
   type: :binary_id
```

```
mix ecto.drop

mix securex.gen.migration

mix ecto.setup
```

**Comment by arduino-man** [comment]
Thanks for your answer.

I've tried both with and without `type: :binary_id` but the result does not change.

Are there any specific logs I can provide? 

Thanks a lot

**Comment by wasitanbits** [comment]
> Thanks for your answer.
> 
> I've tried both with and without `type: :binary_id` but the result does not change.
> 
> Are there any specific logs I can provide?
> 
> Thanks a lot

Yes , Can you please share an `id` from your table?

**Comment by wasibiit** [comment]
@arduino-man Hi, I hope your Issue being Resolved, 
https://hex.pm/packages/securex
